hydra:
  searchpath:
    - file://verl/trainer/config

defaults:
  - ppo_trainer
  - _self_
  
actor_rollout_ref:
  actor:
    _target_: recipe.cppo.cppo_actor_config.FSDPActorConfig
    use_vision_cpl_loss: False
    cpl_loss_coef: 0.01
    cpl_use_vision_mask: False
    cpl_vision_top_percent: 0.5
    cpl_use_advantage_gating: False
    cpl_tau: 0.1

trainer:
  project_name: cppo